site_name: ESAPIハンズオンセミナー2020 
site_author: ESAPIユーザー会 (ESAPI-users-JP)
copyright: "Copyright &copy 2019-2020 ESAPI-users-JP"

# Repository
repo_name: 'ESAPI-users-JP/HandsOnMaterials'
repo_url: 'https://github.com/ESAPI-users-JP/HandsOnMaterials/'
edit_uri: 'edit/master/docs/docs'

nav:
  - はじめに: index.md
  - 1. Hello World in ESAPI:
    - 1.1. ScriptWizardによるスクリプトの生成: 1_HelloWorld/1_1.md
    - 1.2. ESAPI Helpの活用: 1_HelloWorld/1_2.md
  - 2. コードを設計しよう:
    - 2.1. 目的を決めよう: 2_CodeDesign/2_1.md
    - 2.2. チェックしたい内容を決めよう: 2_CodeDesign/2_2.md
  - 3. 患者情報とプラン情報の取得:
    - 3.1. 患者情報の取得: 3_GetPatient/3_1.md
    - 3.2. プラン情報の取得: 3_GetPatient/3_2.md
  - 4. プラン情報のチェック:
    - 4.1. コースID/プランIDのチェック: 4_CheckPlan/4_1.md
    - 4.2. プランNormalizationのチェック: 4_CheckPlan/4_2.md
    - 4.3. 線量計算モデルのチェック: 4_CheckPlan/4_3.md
  - 5. フィールド情報のチェック:
    - 5.1. 治療装置名のチェック: 5_CheckField/5_1.md
    - 5.2. 最小MU/線量率のチェック: 5_CheckField/5_2.md
    - 5.3. 同一アイソセンタのチェック: 5_CheckField/5_3.md
    - 5.4. Jaw/MLC外接距離のチェック: 5_CheckField/5_4.md
    - 5.5. コリジョンのチェック: 5_CheckField/5_5.md
  - 6. リファレンスポイント情報のチェック:
    - 6.1. プライマリリファレンスポイントIDのチェック: 6_CheckRP/6_1.md
    - 6.2. DoseLimitのチェック: 6_CheckRP/6_2.md
    - 6.3. リファレンスポイントと体表面のチェック: 6_CheckRP/6_3.md
    - 6.4. リファレンスポイントのHU値のチェック: 6_CheckRP/6_4.md
  - 7. CT情報のチェック:
    - 7.1. CT-EDテーブルのチェック: 7_CheckCT/7_1.md
    - 7.2. 患者体位のチェック: 7_CheckCT/7_2.md
    - 7.3. 撮影日のチェック: 7_CheckCT/7_3.md
  - 8. 輪郭情報のチェック:
    - 8.1. 輪郭命名規則のチェック: 8_CheckStructure/8_1.md
    - 8.2. HU値オーバーライドのチェック: 8_CheckStructure/8_2.md
    - 8.3. 小体積輪郭のチェック: 8_CheckStructure/8_3.md
  - 9. 線量情報のチェック:
    - 9.1. ターゲットおよびリスク臓器のDVH情報のチェック: 9_CheckDose/9_1.md

theme:
  name: 'material'
  font:
    text: 'Noto Sans JP'
    code: 'Roboto Mono'
  language: 'ja'
  palette:
    primary: 'light blue'
    accent: 'light blue'
extra:
  search:
    language: 'ja'
  social:
    - type: 'github'
      link: 'https://github.com/ESAPI-users-JP'
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.tilde
  - mdx_math:
      enable_dollar_delimiter: true
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
extra_javascript:
  - 'https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js'
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - 'css/extra.css'